---
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD="redhat"
      - MYSQL_DATABASE="student_info"
    volumes:
      - database:/var/lib/mysql
    networks:
      - node_nw
  pma:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql 
    networks:
      - node_nw
    ports:
      - 3030:80

  node_app:
    image: nodeapp:latest
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: "redhat"
      MYSQL_DATABASE: student_info
      MYSQL_HOST: mysql
    ports:
      - 3000:3000
    
    networks:
      - node_nw


volumes:
  database:

networks:
  node_nw:
    